name: AAA
run-name: "AAA for PR #${{ github.event.number }} by @${{ github.actor }}"

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Label: ${{ github.event.label.name }}"
          echo "PR Number: ${{ github.event.number }}"
          echo "Actor: ${{ github.actor }}"

  test-environment:
    if: github.event.label.name == 'test-environment'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Test Environment
        run: |
          echo "Deploying test environment for PR #${{ github.event.number }}"

  other-labels:
    if: github.event.label.name != 'test-environment'
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: |
          echo "Skipping deployment. Label '${{ github.event.label.name }}' is not 'test-environment'"
